spring:
  application:
    name: ManhnnPH34757_Boot
  datasource:
    url: jdbc:mariadb://localhost:3306/exam_distribution_test
    username: root
    password: nguyenmanh2707
  jpa:
    show-sql: true
    open-in-view: true
